name: Mobile Android Release Tests
on:
  workflow_dispatch:
    inputs:
      BUILD_NUMBER:
        description: 'Build Number'
        required: true
        default: 'Android_Latest'

jobs:
  run-android-tests:
    name: Teamsnap Android Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Number
        id: set_build_number
        run: echo "BUILD_NUMBER=Android_Latest" >> $GITHUB_OUTPUT
  call_ads_tests:
    needs: run-android-tests
    uses: ./.github/workflows/android_advertisements.yml
    with:
      BUILD_NUMBER: echo ${{ steps.set_build_number.outputs.BUILD_NUMBER }}
          
