name: Mobile Android Advertisement Tests
on:
  workflow_call:
    inputs:
      BUILD_NUMBER:
        description: 'Build Number'
        required: true
        type: string
        default: 'Android_Latest'
  workflow_dispatch:
    inputs:
      BUILD_NUMBER:
        description: 'Build Number'
        required: true
        default: 'Android_Latest'

jobs:
  run-android-tests:
    name: Teamsnap Android Advertisement Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Number
        id: set_build_number
        run: echo ${{ inputs.BUILD_NUMBER }}
  call_compatibility_tests:
    uses: ./.github/workflows/android_compatibility.yml
    with:
      BUILD_NUMBER: ${{ inputs.BUILD_NUMBER }}
